import { v4 as uuid } from "uuid";

const citiesList = [
  {
    id: uuid(),
    city: "Hyderabad",
    areas: [
      {
        id: uuid(),
        areaName: "Durgam Cheruvu",
        locationLink: "https://maps.app.goo.gl/991hkkwxP7FDfxwU9",
        slots: [
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00AM - 9:00AM",
            slotExpiry: "7:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00AM - 10:00AM",
            slotExpiry: "8:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "10:00AM - 11:00AM",
            slotExpiry: "9:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "11:00AM - 12:00PM",
            slotExpiry: "10:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "12:00PM - 1:00PM",
            slotExpiry: "11:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "1:00PM - 2:00PM",
            slotExpiry: "12:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "2:00PM - 3:00PM",
            slotExpiry: "1:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "3:00PM - 4:00PM",
            slotExpiry: "2:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "4:00PM - 5:00PM",
            slotExpiry: "3:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "5:00PM - 6:00PM",
            slotExpiry: "4:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "6:00PM - 7:00PM",
            slotExpiry: "5:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "7:00PM - 8:00PM",
            slotExpiry: "6:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00PM - 9:00PM",
            slotExpiry: "7:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00PM - 10:00PM",
            slotExpiry: "8:50PM",
          },
        ],
      },
      {
        id: uuid(),
        areaName: "Madhapur",
        locationLink: "https://maps.app.goo.gl/991hkkwxP7FDfxwU9",
        slots: [
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00AM - 9:00AM",
            slotExpiry: "7:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00AM - 10:00AM",
            slotExpiry: "8:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "10:00AM - 11:00AM",
            slotExpiry: "9:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "11:00AM - 12:00PM",
            slotExpiry: "10:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "12:00PM - 1:00PM",
            slotExpiry: "11:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "1:00PM - 2:00PM",
            slotExpiry: "12:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "2:00PM - 3:00PM",
            slotExpiry: "1:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "3:00PM - 4:00PM",
            slotExpiry: "2:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "4:00PM - 5:00PM",
            slotExpiry: "3:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "5:00PM - 6:00PM",
            slotExpiry: "4:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "6:00PM - 7:00PM",
            slotExpiry: "5:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "7:00PM - 8:00PM",
            slotExpiry: "6:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00PM - 9:00PM",
            slotExpiry: "7:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00PM - 10:00PM",
            slotExpiry: "8:50PM",
          },
        ],
      },
    ],
  },
  {
    id: uuid(),
    city: "Chennai",
    locationLink: "https://maps.app.goo.gl/991hkkwxP7FDfxwU9",
    areas: [
      {
        id: uuid(),
        areaName: "Besant Nagar",
        slots: [
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00AM - 9:00AM",
            slotExpiry: "7:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00AM - 10:00AM",
            slotExpiry: "8:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "10:00AM - 11:00AM",
            slotExpiry: "9:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "11:00AM - 12:00PM",
            slotExpiry: "10:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "12:00PM - 1:00PM",
            slotExpiry: "11:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "1:00PM - 2:00PM",
            slotExpiry: "12:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "2:00PM - 3:00PM",
            slotExpiry: "1:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "3:00PM - 4:00PM",
            slotExpiry: "2:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "4:00PM - 5:00PM",
            slotExpiry: "3:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "5:00PM - 6:00PM",
            slotExpiry: "4:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "6:00PM - 7:00PM",
            slotExpiry: "5:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "7:00PM - 8:00PM",
            slotExpiry: "6:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00PM - 9:00PM",
            slotExpiry: "7:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00PM - 10:00PM",
            slotExpiry: "8:50PM",
          },
        ],
      },
      {
        id: uuid(),
        areaName: "Anna Nagar",
        locationLink: "https://maps.app.goo.gl/991hkkwxP7FDfxwU9",
        slots: [
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00AM - 9:00AM",
            slotExpiry: "7:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00AM - 10:00AM",
            slotExpiry: "8:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "10:00AM - 11:00AM",
            slotExpiry: "9:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "11:00AM - 12:00PM",
            slotExpiry: "10:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "12:00PM - 1:00PM",
            slotExpiry: "11:50AM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "1:00PM - 2:00PM",
            slotExpiry: "12:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "2:00PM - 3:00PM",
            slotExpiry: "1:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "3:00PM - 4:00PM",
            slotExpiry: "2:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "4:00PM - 5:00PM",
            slotExpiry: "3:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "5:00PM - 6:00PM",
            slotExpiry: "4:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "6:00PM - 7:00PM",
            slotExpiry: "5:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "7:00PM - 8:00PM",
            slotExpiry: "6:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "8:00PM - 9:00PM",
            slotExpiry: "7:50PM",
          },
          {
            id: uuid(),
            bookingStatus: false,
            timeSlot: "9:00PM - 10:00PM",
            slotExpiry: "8:50PM",
          },
        ],
      },
    ],
  },
];

export default citiesList;
